name: Lint, Test, Security Checks, and Versioning

on:
  push:
    branches:
      - main 

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  hadolint:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.hadolint_outcome.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        id: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          failure-threshold: error
          format: json

  code_lint:
    runs-on: ubuntu-latest
    needs: hadolint
    outputs:
      code_lint_result: ${{ steps.code_lint_outcome.outputs.code_lint_result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Code lint
        id: code_lint
        run: |
          npm i
          set -o pipefail
          npm run lint 2>&1 

  unit_tests:
    runs-on: ubuntu-latest
    needs: code_lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unit tests
        id: unit_tests
        run: |
          npm i
          set -o pipefail
          npm run test 2>&1

  build-and-push:
    runs-on: ubuntu-latest
    needs: unit_tests   #

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }} #Prvo generisem token (repo write packages) Token na Githubu. Moram da napravim u Github Actions New repository secret i tu ubacim vrednost iz Tokena.

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}

    - name: Logout from GitHub Container Registry
      run: docker logout ghcr.io
